//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23WebAPIAssignment1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class PoDetail
    {

        [DisplayName("Purchase No")]
        public string PoNo { get; set; }

        [DisplayName("Item code")]
        public string Itcode { get; set; }
        [Required]
        [DisplayName("Qunatity")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Qunatity invalid")]
        public Nullable<int> Qty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual PoMaster PoMaster { get; set; }
        public virtual PoDetail PoDetail1 { get; set; }
        public virtual PoDetail PoDetail2 { get; set; }
        public virtual List<SelectListItem> Items { get; set; }
        public virtual List<SelectListItem> PoNos { get; set; }
    }
}
