//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23WebAPIAssignment1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class PoMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoMaster()
        {
            this.PoDetails = new HashSet<PoDetail>();
        }

        [Required]
        [StringLength(4, ErrorMessage = "String length can be max 4")]
        [DisplayName("Purchase No")]
        public string PoNo { get; set; }
        [Required]
        [DisplayName("Purchase Date")]
        public Nullable<System.DateTime> PoDate { get; set; }
        [Required]
        [DisplayName("Supplier No")]
        public string SuplNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoDetail> PoDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual List<SelectListItem> Suppliers { get; set; }
    }
}
