//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23WebAPIAssignment1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.PoMasters = new HashSet<PoMaster>();
        }
        [Required]
        [StringLength(4,ErrorMessage ="String length can be max 4")]
        [DisplayName("Supplier No")]
        public string SuplNo { get; set; }
        [Required]
        [DisplayName("Supplier Name")]
        public string SuplName { get; set; }
        [Required]
        [DisplayName("Supplier Address")]
        public string SuplAddr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoMaster> PoMasters { get; set; }
    }
}
